baseURL = 'https://jonastoth.github.io/'
languageCode = 'en-us'
title = 'Jonas Toth'
theme = 'gokarna'
enableRobotsTXT = true

[menu]
  # "weight" defines the ordering in the menu
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/JonasToth"
    pre = "<span data-feather='github'></span>"
    name = "Github"
    weight = 1
    [menu.main.params]
        newPage = true

  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "about"
    url = "/about/"
    pre = "<span data-feather='user'></span>"
    name = "About"
    weight = 2

  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "publications"
    url = "/publications/"
    pre = "<span data-feather='file-text'></span>"
    name = "Publications"
    weight = 3
  [[menu.main]]
    identifier = "curiositas"
    url = "https://curiositasbooks.gumroad.com/"
    pre = "<span data-feather='book'></span>"
    name = "Curiositas"
    weight = 4
    
[params]
    footer = "All Rights Reserved"
    showPostsOnHomePage = "popular"
    socialIcons = [
      {name = "buymeacoffee", url = "https://curiositasbooks.gumroad.com/"},
      {name = "github", url = "https://github.com/JonasToth"},
      {name = "linkedin", url = "https://www.linkedin.com/in/jonas-toth-a4449a16b/"},
    ]
    accentColor = "#08F"
    customHeadHTML = '''
    <link rel="stylesheet" type="text/css" href="/css/extension.css">
    '''

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

